const { schedule } = require('node-cron')
const run = require('./run-xvfb')
// const runner = require('./runner')
// schedule('*/30 * * * *', async () => await runner())
schedule('16 6,8,15 * * *', () => run())